repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: ⚙️ Check YAML
      - id: check-toml
        name: ⚙️ Check TOML
      - id: end-of-file-fixer
        name: ⚙️ End of file fixer
      - id: trailing-whitespace
        name: ⚙️ Trailing whitespace remover
      - id: check-case-conflict
        name: ⚙️ Check case conflict
      - id: check-docstring-first
        name: ⚙️ Check docstring first
      - id: check-merge-conflict
        name: ⚙️ Check merge conflict
      - id: detect-private-key
        name: ⚙️ Detect private key
      - id: debug-statements
        name: "⚙️ Check debug statements"
  - repo: https://github.com/oxipng/oxipng
    rev: v9.1.5
    hooks:
      - id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]
